"""
BudgetX - AI Polishing Layer (Gemini Flash)
"""

from ai_utils import get_gemini_model

def polish_with_flash(text: str) -> str:
    """Polishes and formats the output from the local model using Gemini Flash."""
    ai_model = get_gemini_model()
    if ai_model is None:
        return text # Return original if Gemini is unavailable
    
    prompt = f"""You are a professional financial advisor. Below is a raw financial advice draft generated by a local model. 
Please polish it for clarity, professionalism, and conciseness. 
Maintain the core message but make it more structured and readable.

Raw Advice:
{text}

Polished Advice:"""

    try:
        response = ai_model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"Polishing failed: {str(e)}")
        return text
